"""empty message

Revision ID: 9eb639544739
Revises: f94dd6a6b9d1
Create Date: 2019-05-28 22:02:49.977894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9eb639544739'
down_revision = 'f94dd6a6b9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('alts', sa.Text(), nullable=True),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('phrags', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('phrags', 'create_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrags', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('phrags', 'created_at')
    op.drop_table('tags')
    # ### end Alembic commands ###
